
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {

    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarInset,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
    SidebarProvider,

} from "@/components/ui/sidebar";

import {cookies} from "next/headers";
import Link from "next/link";

import {SiteHeader} from "@/components/layout/site-header";
import {Toaster} from "@/components/ui/sonner";
import AppSidebarNavMain from "@/components/layout/appsidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function IconInnerShadowTop(props: { className: string }) {
    return null;
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SidebarProvider
          style={
              {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
              } as React.CSSProperties
          }
      >
          <Sidebar collapsible="offcanvas" variant="inset">
              <SidebarHeader>
                  <SidebarMenu>
                      <SidebarMenuItem>
                          <SidebarMenuButton
                              asChild
                              className="data-[slot=sidebar-menu-button]:!p-1.5"
                          >
                              <Link href="/app">
                                  <IconInnerShadowTop className="!size-5" />
                                  <span className="text-base font-semibold">Acme Inc.</span>
                              </Link>
                          </SidebarMenuButton>
                      </SidebarMenuItem>
                  </SidebarMenu>
              </SidebarHeader>
              <SidebarContent>
                <AppSidebarNavMain/>
              </SidebarContent>
              <SidebarFooter>
                  {/*<NavUser user={data.user} />*/}
              </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            <SiteHeader/>
              <main className="flex flex-1 flex-col">
                  <div className="@container/main flex flex-1 flex-col gap-2">
                      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
                          {children}
                      </div>
                  </div>
              </main>
              <Toaster />
          </SidebarInset>
      </SidebarProvider>

      </body>
    </html>
  );
}
